# Generated by Django 5.1.6 on 2025-03-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ator',
            fields=[
                ('nome', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('titulo', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('ano', models.IntegerField()),
                ('diretor', models.CharField(max_length=100)),
                ('sinopse', models.TextField()),
                ('atores', models.ManyToManyField(related_name='filmes', to='Buscafilme.ator')),
            ],
        ),
    ]
