# Generated by Django 5.1.6 on 2025-03-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buscafilme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ator',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
